# Local clock
[[clocks]]
name = "ğŸ’»"

# California
[[clocks]]
name = "â˜€ï¸"
tz = "America/Los_Angeles"

# Home
[[clocks]]
name = "ğŸ "
tz = "America/Chicago"

# UTC
[[clocks]]
name = "â°"
tz = "UTC"

# London
[[clocks]]
name = "ğŸ‡¬ğŸ‡§"
tz = "Europe/London"

# London
[[clocks]]
name = "ğŸ‡ºğŸ‡¦"
tz = "Europe/Kiev"

# Sydney
[[clocks]]
name = "ğŸ¨"
tz = "Australia/Sydney"
